V4.1.8 Bug fixing
* Fixed NoSuchMethodError:
org.bukkit.event.entity.ProjectileHitEvent.getHitEntity() on older
Minecraft versions. If you get this error on Minecraft 1.11 you need to
update SpigotMC.
(https://www.spigotmc.org/threads/mobhunting.46937/page-70#post-2065080)
* Money rewards can now disappear, if hit by f.ex. a fireball.