V3.4.0 Bug fixing
* Fixed bug on servers < Minecraft 1.10: NoSuchMethodError:
org.bukkit.entity.Zombie.getVillagerProfession() 
* Missing mobhunting.commands.region.description added to Lang files.
* /mh help has been updated, including /mh <command> help